# Generated by Django 4.1.3 on 2022-11-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapper',
            fields=[
                ('scrapper_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scrapper_jobs_log_id', models.IntegerField()),
                ('external_job_source_id', models.IntegerField()),
                ('start_time', models.DateTimeField(default=True)),
                ('end_time', models.DateTimeField(default=True)),
                ('scrapper_status', models.IntegerField()),
                ('processed_records', models.IntegerField()),
                ('new_records', models.IntegerField()),
                ('skipped_records', models.IntegerField()),
                ('error_records', models.IntegerField()),
            ],
            options={
                'db_table': 'scrapper_job_logs',
            },
        ),
    ]
